export const categories = [
  {
    name: "Music",
    topics: [
      "Pop",
      "Rock",
      "Hip Hop",
      "Electronic",
      "Jazz",
      "Classical",
      "R&B",
      "Country",
      "Metal",
      "Indie",
      "K-Pop",
      "Reggae",
      "Blues",
      "Folk",
      "Punk",
      "Disco",
      "EDM",
      "Lo-Fi",
      "Synthwave",
      "Gospel",
      "Orchestral",
      "World Music",
    ],
  },
  {
    name: "Gaming",
    topics: [
      "PC Gaming",
      "Console Gaming",
      "Mobile Gaming",
      "Esports",
      "Game Development",
      "Retro Gaming",
      "VR Gaming",
      "Speedrunning",
      "Board Games",
      "Tabletop RPGs",
      "FPS",
      "RPG",
      "MMORPG",
      "Strategy",
      "Simulation",
      "Horror Games",
      "Fighting Games",
      "Racing Games",
      "Sandbox",
      "Indie Games",
      "Game Mods",
    ],
  },
  {
    name: "Technology",
    topics: [
      "Programming",
      "Artificial Intelligence",
      "Cybersecurity",
      "Web Development",
      "Data Science",
      "Machine Learning",
      "Blockchain",
      "Cloud Computing",
      "DevOps",
      "Mobile Development",
      "UI/UX Design",
      "Hardware",
      "Robotics",
      "Quantum Computing",
      "Networking",
      "Open Source",
      "Tech News",
      "Linux",
      "iOS",
      "Android",
      "Self-Hosted",
    ],
  },
  {
    name: "Sports",
    topics: [
      "Football (Soccer)",
      "Basketball",
      "Tennis",
      "Swimming",
      "Cycling",
      "Running",
      "American Football",
      "Baseball",
      "Cricket",
      "Golf",
      "MMA",
      "Boxing",
      "Volleyball",
      "Rugby",
      "Formula 1",
      "Olympics",
      "Skiing",
      "Snowboarding",
      "Surfing",
      "Skateboarding",
      "Hockey",
      "Badminton",
    ],
  },
  {
    name: "Movies & TV",
    topics: [
      "Action",
      "Comedy",
      "Horror",
      "Sci-Fi",
      "Documentary",
      "Animation",
      "Drama",
      "Thriller",
      "Romance",
      "Fantasy",
      "Superhero",
      "Crime",
      "Mystery",
      "Western",
      "Anime",
      "Bollywood",
      "Classic Films",
      "TV Shows",
      "Streaming",
      "Film Theory",
      "Movie Memes",
    ],
  },
  {
    name: "Books & Literature",
    topics: [
      "Fiction",
      "Non-Fiction",
      "Fantasy",
      "Science Fiction",
      "Biography",
      "Mystery",
      "Romance",
      "Horror",
      "Historical Fiction",
      "Poetry",
      "Self-Help",
      "Philosophy",
      "Young Adult",
      "Graphic Novels",
      "Classics",
      "Crime",
      "Thriller",
      "Literary Fiction",
      "Short Stories",
      "Book Clubs",
    ],
  },
  {
    name: "Food & Cooking",
    topics: [
      "Cooking",
      "Baking",
      "Vegan",
      "BBQ",
      "Desserts",
      "International Cuisine",
      "Italian",
      "Japanese",
      "Mexican",
      "Indian",
      "Chinese",
      "Mediterranean",
      "Keto",
      "Meal Prep",
      "Food Photography",
      "Restaurant Reviews",
      "Cocktails",
      "Coffee",
      "Tea",
      "Fermentation",
      "Food Science",
    ],
  },
  {
    name: "Travel & Adventure",
    topics: [
      "Backpacking",
      "Luxury Travel",
      "Road Trips",
      "Hiking",
      "Beach Destinations",
      "Solo Travel",
      "Budget Travel",
      "Camping",
      "National Parks",
      "Ski Resorts",
      "Urban Exploration",
      "Digital Nomads",
      "Travel Photography",
      "Hidden Gems",
      "Adventure Sports",
      "Cruises",
      "Eco-Tourism",
      "Historical Sites",
      "Van Life",
    ],
  },
  {
    name: "Fitness & Health",
    topics: [
      "Weightlifting",
      "Yoga",
      "CrossFit",
      "Running",
      "Calisthenics",
      "Nutrition",
      "Bodybuilding",
      "Pilates",
      "Martial Arts",
      "Meditation",
      "Mental Health",
      "Weight Loss",
      "Intermittent Fasting",
      "Physical Therapy",
      "Supplements",
      "Home Workouts",
      "Sports Medicine",
      "Longevity",
      "Sleep Optimization",
    ],
  },
  {
    name: "Art & Creativity",
    topics: [
      "Painting",
      "Digital Art",
      "Photography",
      "Sculpture",
      "Street Art",
      "Illustration",
      "Concept Art",
      "3D Modeling",
      "Calligraphy",
      "Graffiti",
      "Tattoo Art",
      "Crafts",
      "Woodworking",
      "Pottery",
      "Fashion Design",
      "Creative Writing",
      "Filmmaking",
      "Music Production",
      "DIY Projects",
      "Memes",
    ],
  },
  {
    name: "Science & Nature",
    topics: [
      "Astronomy",
      "Physics",
      "Biology",
      "Chemistry",
      "Geology",
      "Environmental Science",
      "Paleontology",
      "Neuroscience",
      "Psychology",
      "Space Exploration",
      "Climate Change",
      "Wildlife",
      "Botany",
      "Oceanography",
      "Archaeology",
      "Futurology",
      "DIY Science",
      "Science Memes",
    ],
  },
  {
    name: "Finance & Business",
    topics: [
      "Personal Finance",
      "Investing",
      "Stock Market",
      "Cryptocurrency",
      "Real Estate",
      "Entrepreneurship",
      "Startups",
      "Side Hustles",
      "FIRE (Financial Independence)",
      "Economics",
      "Accounting",
      "Marketing",
      "Freelancing",
      "Career Advice",
      "Business News",
      "Taxes",
      "Budgeting",
      "Passive Income",
    ],
  },
  {
    name: "Hobbies & Lifestyle",
    topics: [
      "Gardening",
      "Home Improvement",
      "Collecting",
      "Board Games",
      "Pets",
      "Aquariums",
      "Birdwatching",
      "Fishing",
      "Knitting",
      "Guns & Shooting",
      "Watches",
      "Cars",
      "Motorcycles",
      "Cycling",
      "Minimalism",
      "Parenting",
      "Relationships",
      "Fashion",
      "Beauty",
      "Luxury Lifestyle",
    ],
  },
  {
    name: "Politics & Society",
    topics: [
      "World News",
      "US Politics",
      "European Politics",
      "Social Justice",
      "History",
      "Philosophy",
      "Law",
      "Education",
      "Urban Planning",
      "Feminism",
      "Environmentalism",
      "Human Rights",
      "Debate",
      "Conspiracy Theories",
      "Current Events",
      "Geopolitics",
      "Activism",
      "Non-Profit",
    ],
  },
  {
    name: "Humor & Memes",
    topics: [
      "Dank Memes",
      "Wholesome Memes",
      "Dark Humor",
      "Surreal Memes",
      "Puns",
      "Dad Jokes",
      "Satire",
      "Roast Me",
      "Cursed Images",
      "Internet Culture",
      "Reaction GIFs",
      "Niche Memes",
      "Cringe",
      "Stand-Up Comedy",
      "Parodies",
    ],
  },
  {
    name: "Miscellaneous",
    topics: [
      "AMA (Ask Me Anything)",
      "TIL (Today I Learned)",
      "Shower Thoughts",
      "Life Pro Tips",
      "Unpopular Opinions",
      "Oddly Satisfying",
      "Uplifting News",
      "Creepy Stories",
      "Glitch in the Matrix",
      "Writing Prompts",
      "AITA (Am I the A**hole?)",
    ],
  },
];
